version = 0.1
[default.deploy.parameters]
stack_name = "sam-id-2012-x"
resolve_s3 = true
s3_prefix = "sam-id-2012-x"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "s3Bucket=\"kandidat-2012\""

