AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  VerneVokterne PPE Checking


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 512

Parameters:
  s3Bucket:
    Type: String
    Description: image bucket for PPE recognition
  ApiPath:
    Type: String
    Default: /check



Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref s3Bucket


  PPEScannerFunction:
    DependsOn: Bucket
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ppe_check/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaS3RecognitionRole.Arn
      Runtime: python3.9
      Environment:
        Variables:
          BUCKET_NAME: !Ref s3Bucket
      Architectures:
        - x86_64

      Events:
        CheckForPPE:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: Fn::Sub "${ApiPath}"
            Method: get
  LambdaS3RecognitionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: "/"
      Policies:
        - PolicyName: rekon
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'rekognition:*'
                Resource: '*'
        - PolicyName: s3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 's3:*'
                  - 's3-object-lambda:*'
                Resource:
                  - "*"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CheckForPPEApi:
    Description: "API Gateway endpoint URL for Prod stage for PPE Scanner function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod${ApiPath}/"
  PPEScannerFunction:
    Description: "PPE Scanner  Lambda Function ARN"
    Value: !GetAtt PPEScannerFunction.Arn
  PPEScannerFunctionIamRole:
    Description: "Implicit IAM Role created for PPE Scanner function"
    Value: !GetAtt LambdaS3RecognitionRole.Arn
