name: Build and Deploy SAM
on:
  push:
    branches:
      - main
env:
  S3_IMAGE_BUCKET: sam-image-s3-2012 # this needs to be empty if recreating
  STACK_NAME: sam-ppe-scan-2012
  S3_ARTIFACT: artifact-2012
defaults:
  run:
    working-directory: ./kjell

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - run: sam build  --use-container
      - run: sam deploy --stack-name ${{ env.STACK_NAME }} --s3-bucket ${{ env.S3_ARTIFACT }} --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides s3Bucket=${{ env.S3_IMAGE_BUCKET }}